const gerontologists = [
    {
        "affiliationCategory": "COST International Partners",
        "country": "Australia",
        "email": "alyse.sue@genomix.co",
        "expertise": "Computer and Information Sciences (Regenerative medicine for life and health extension)",
        "gender": "Female",
        "institution": "Genomix",
        "location": {lat: -35.3136188, lng: 148.9896987},
        "name": "Ms Alyse Sue",
        "phone": "+61405838333",
        "yearOfBirth": "1988",
        "yearsSincePHD": "0"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Austria",
        "email": "Barbara.Strasser@i",
        "expertise": "Health Sciences (Sport and fitness sciences)",
        "gender": "Female",
        "institution": "Medical University Innsbruck",
        "location": {lat: 47.262698, lng: 11.3827692},
        "name": "Prof Barbara Strasser",
        "phone": "+436642083316",
        "yearOfBirth": "1972",
        "yearsSincePHD": "8"
    },
    {
        "affiliationCategory": "COST International Partners",
        "country": "Bangladesh",
        "email": "rimaruf@grameen.com",
        "expertise": "Electrical engineering, electronic engineering, Information engineering (Communications engineering and systems)",
        "gender": "Male",
        "institution": "Grameen Communications",
        "location": {lat: 23.1943498, lng: 87.7778257},
        "name": "Dr Rafiqul Islam",
        "phone": "+88029016391",
        "yearOfBirth": "1967",
        "yearsSincePHD": "19"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Belgium",
        "email": "Liesbet.Temmerman@bio.kuleuven.be",
        "expertise": "Biological sciences (Molecular biology and interactions)",
        "gender": "Female",
        "institution": "University of Leuven ",
        "location": {lat: 50.8779579, lng: 4.6981066},
        "name": "Prof Liesbet Temmerman",
        "phone": "+3216324260",
        "yearOfBirth": "1985",
        "yearsSincePHD": "5"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Belgium",
        "email": "didier.coeurnelle@gmail.com",
        "expertise": "Health Sciences (Health services, health care research)",
        "gender": "Male",
        "institution": "Heales",
        "location": {lat: 51.2605163, lng: 4.2304522},
        "name": "Mr Didier Coeurnelle",
        "phone": "+3224105956",
        "yearOfBirth": "1962",
        "yearsSincePHD": "0"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Belgium",
        "email": "arne@academiclabs.co",
        "expertise": "Biological sciences (Zoology, including animal behaviour)",
        "gender": "Male",
        "institution": "AcademicLabs",
        "location": {lat: 51.2605160, lng: 4.2304500},
        "name": "Mr Arne Smolders",
        "phone": "+32479509327",
        "yearOfBirth": "1988",
        "yearsSincePHD": "0"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Bulgaria",
        "email": "angel_marchev@yahoo.co.uk",
        "expertise": "Economics and business (Databases, data mining, data curation, computational modelling)",
        "gender": "Male",
        "institution": "University of National and World Economy",
        "location": {lat: 42.6512699, lng: 23.3466593},
        "name": "Prof Angel Marchev",
        "phone": "+35929833991",
        "yearOfBirth": "1946",
        "yearsSincePHD": "35"
    },
    {
        "affiliationCategory": "COST International Partners",
        "country": "Canada",
        "email": "arnold.mitnitski@dal.ca",
        "expertise": "Health Sciences (Applied mathematics, statistics, non-computational modeling for health sciences)",
        "gender": "Male",
        "institution": "Dalhousie University",
        "location": {lat: 44.636585, lng: -63.5938442},
        "name": "Dr Arnold Mitnitski",
        "phone": "+9024460460",
        "yearOfBirth": "1944",
        "yearsSincePHD": "42"
    },
    {
        "affiliationCategory": "COST International Partners",
        "country": "Canada",
        "email": "tamas.fulop@usherbrooke.ca",
        "expertise": "Basic medicine (Cell signalling and cellular interactions)",
        "gender": "Male",
        "institution": "Universit\u00e9 de Sherbrooke - Facult\u00e9 de m\u00e9decine et des Sciences de la sant\u00e9",
        "location": {lat: 45.3768923, lng: -71.9277091},
        "name": "Prof Tamas Fulop",
        "phone": "+18197802220",
        "yearOfBirth": "1953",
        "yearsSincePHD": "31"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Cyprus",
        "email": "drmarios@live.it",
        "expertise": "Biological sciences (Biology of Ageing)",
        "gender": "Male",
        "institution": "Cyprus Neuroscienec and Technology Institute - CNTI",
        "location": {lat: 35.165786, lng: 33.3569552},
        "name": "Dr Marios Kyriazis",
        "phone": "+447850221796",
        "yearOfBirth": "1956",
        "yearsSincePHD": "32"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Cyprus",
        "email": "fofic@ucy.ac.cy",
        "expertise": "",
        "gender": "Female",
        "institution": "University of Cyprus",
        "location": {lat: 35.1600058, lng: 33.3748288},
        "name": "Prof Fofi Constantinidou",
        "phone": "+35722892078",
        "yearOfBirth": "1966",
        "yearsSincePHD": "21"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Czech Republic",
        "email": "radislav.sedlacek@img.cas.cz",
        "expertise": "Biological sciences (Molecular genetics, reverse genetics and RNAi)",
        "gender": "Male",
        "institution": "Institute of Molecular Genetics of the ASCR",
        "location": {lat: 50.0178296, lng: 14.4642586},
        "name": "Dr Radislav Sedlacek",
        "phone": "+420325873243",
        "yearOfBirth": "1965",
        "yearsSincePHD": "19"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Denmark",
        "email": "rattan@mbg.au.dk",
        "expertise": "Biological sciences (Ageing, gerontology, stress, hormesis, hormetics, skin, health, longevity)",
        "gender": "Male",
        "institution": "Aarhus University",
        "location": {lat: 56.1681414, lng: 10.2008231},
        "name": "Dr Suresh Rattan",
        "phone": "+4587155436",
        "yearOfBirth": "1955",
        "yearsSincePHD": "21"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "France",
        "email": "antonkulaga@gmail.com",
        "expertise": "Computer and Information Sciences (Machine learning algorithms)",
        "gender": "Male",
        "institution": "International Longevity Alliance - Interantional Longevity Alliance",
        "location": {lat: 48.8589507, lng: 2.2775172},
        "name": "Mr Anton Kulaga",
        "phone": "+380964221181",
        "yearOfBirth": "1986",
        "yearsSincePHD": "0"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "France",
        "email": "edebonneuil@yahoo.fr",
        "expertise": "Clinical medicine (Respiratory systems)",
        "gender": "Male",
        "institution": "ActuRx",
        "location": {lat: 48.8589500, lng: 2.2775173},
        "name": "Dr Edouard Debonneuil",
        "phone": "+0652076562",
        "yearOfBirth": "1980",
        "yearsSincePHD": "10"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "France",
        "email": "eric.gilson@unice.fr",
        "expertise": "Biological sciences (DNA synthesis, modification, repair, recombination and degradation)",
        "gender": "Male",
        "institution": "University of Nice Sophia Antipolis",
        "location": {lat: 43.7099538, lng: 7.2874749},
        "name": "Prof Eric Gilson",
        "phone": "+33607272973",
        "yearOfBirth": "1958",
        "yearsSincePHD": "12"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Germany",
        "email": "leis.miriam@gmx.de",
        "expertise": "Political Science (Strategic Technology Foresight)",
        "gender": "Female",
        "institution": "Fraunhofer-Gesellschaft",
        "location": {lat: 49.4371119, lng: 8.2447229},
        "name": "Dr Miriam Leis",
        "phone": "+017263",
        "yearOfBirth": "1976",
        "yearsSincePHD": "11"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Germany",
        "email": "fuellen@uni",
        "expertise": "Computer and Information Sciences (Ageing Research)",
        "gender": "Male",
        "institution": "Rostock University Medical Center",
        "location": {lat: 54.0890813, lng: 7.6350453},
        "name": "Prof Georg Fuellen",
        "phone": "+4903814947361",
        "yearOfBirth": "1967",
        "yearsSincePHD": "16"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Germany",
        "email": "ludger.jansen@uni",
        "expertise": "Philosophy",
        "gender": "Male",
        "institution": "Ruhr-University Bochum",
        "location": {lat: 51.4456692, lng: 7.2594206},
        "name": "Dr Ludger Jansen",
        "phone": "+493812102852",
        "yearOfBirth": "1969",
        "yearsSincePHD": "15"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Germany",
        "email": "tschaech@gmx.de",
        "expertise": "Biological sciences (Molecular biology and interactions)",
        "gender": "Male",
        "institution": "MSD Sharp",
        "location": {lat: 50.2950608, lng: 10.3196954},
        "name": "Dr Thorsten Schaechinger",
        "phone": "+4915205305436",
        "yearOfBirth": "1978",
        "yearsSincePHD": "9"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Germany",
        "email": "martin@age.mpg.de",
        "expertise": "Biological sciences (Molecular biology and interactions)",
        "gender": "Male",
        "institution": "Max Planck Society - Max Planck Institute for Biology of Ageing",
        "location": {lat: 50.9252977, lng: 6.9171289},
        "name": "Dr Martin Denzel",
        "phone": "+4922137970443",
        "yearOfBirth": "1979",
        "yearsSincePHD": "7"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Germany",
        "email": "",
        "expertise": "Biological sciences (Bioinformatics)",
        "gender": "Male",
        "institution": "Fraunhofer Gesellschaft zur Foerderung der Wissenschaft e.V. - Fraunhofer Institute for Algorithms and Scientific Computing (SCAI)",
        "location": {lat: 50.8889357, lng: 6.9846567},
        "name": "Prof Martin Hofmann-Apitius",
        "phone": "+492241142802",
        "yearOfBirth": "1961",
        "yearsSincePHD": "25"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Greece",
        "email": "sgonos@eie.gr",
        "expertise": "Biological sciences (Protein synthesis",
        "gender": "Male",
        "institution": "National Hellenic Research Foundation",
        "location": {lat: 37.9733564, lng: 23.7433258},
        "name": "Dr Efstathios Gonos",
        "phone": "+302107273756",
        "yearOfBirth": "1963",
        "yearsSincePHD": "27"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Hungary",
        "email": "antal@mit.bme.hu",
        "expertise": "Computer and Information Sciences (Machine learning algorithms)",
        "gender": "Male",
        "institution": "Budapest University of Technology and Economics",
        "location": {lat: 47.4813297, lng: 19.0532947},
        "name": "Dr Peter Antal",
        "phone": "+36305630041",
        "yearOfBirth": "1971",
        "yearsSincePHD": "8"
    },
    {
        "affiliationCategory": "COST International Partners",
        "country": "India",
        "email": "akondapi@gmail.com",
        "expertise": "Biological sciences (DNA synthesis",
        "gender": "Male",
        "institution": "University of Hyderabad",
        "location": {lat: 17.4624641, lng: 78.3311253},
        "name": "Prof Anand Kumar Kondapi",
        "phone": "+914023134571",
        "yearOfBirth": "1963",
        "yearsSincePHD": "26"
    },
    {
        "affiliationCategory": "COST International Partners",
        "country": "India",
        "email": "ksrbrain@gmail.com",
        "expertise": "Biological sciences (DNA synthesis",
        "gender": "Male",
        "institution": "University of Hyderabad",
        "location": {lat: 17.4624640, lng: 78.3311250},
        "name": "Prof Subba Rao Kalluri",
        "phone": "+914023112619",
        "yearOfBirth": "1939",
        "yearsSincePHD": "51"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Israel",
        "email": "ilia.stambler@gmail.com",
        "expertise": "Biological sciences (History and philosophy of biology)",
        "gender": "Male",
        "institution": "Bar Ilan University",
        "location": {lat: 32.0692034, lng: 34.8408989},
        "name": "Dr Ilia Stambler",
        "phone": "+97239614296",
        "yearOfBirth": "1972",
        "yearsSincePHD": "4"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Israel",
        "email": "gatzmon@univ.haifa.ac.il",
        "expertise": "Biological sciences (Genomics)",
        "gender": "Male",
        "institution": "University of haifa",
        "location": {lat: 32.7614341, lng: 35.0173297},
        "name": "Prof Gil Atzmon",
        "phone": "+97248280765",
        "yearOfBirth": "1963",
        "yearsSincePHD": "12"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Israel",
        "email": "valery.krizhanovsky@weizmann.ac.il",
        "expertise": "Biological sciences (Cell cycle and division)",
        "gender": "Male",
        "institution": "Weizmann Institute of Science",
        "location": {lat: 31.9043529, lng: 34.8076541},
        "name": "Dr Valery Krizhanovsky",
        "phone": "+97289346575",
        "yearOfBirth": "1970",
        "yearsSincePHD": "10"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Italy",
        "email": "francesca.cirulli@iss.it",
        "expertise": "Biological sciences (Neurobiology of stress in health and disease)",
        "gender": "Female",
        "institution": "Istituto Superiore di Sanita",
        "location": {lat: 41.9061189, lng: 12.5178463},
        "name": "Dr Francesca Cirulli",
        "phone": "+00390649902480",
        "yearOfBirth": "1965",
        "yearsSincePHD": "16"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Italy",
        "email": "calogero.caruso@unipa.it",
        "expertise": "Basic medicine (Immunogenetics)",
        "gender": "Male",
        "institution": "University of Palermo",
        "location": {lat: 38.1177942, lng: 13.3676493},
        "name": "Prof Calogero Caruso",
        "phone": "+390916555911",
        "yearOfBirth": "1947",
        "yearsSincePHD": "45"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Italy",
        "email": "paolo.garagnani2@unibo.it",
        "expertise": "Biological sciences (Genomics, comparative genomics, functional genomics)",
        "gender": "Male",
        "institution": "Alma Mater Studiorum University degli Studi di Bologna",
        "location": {lat: 44.4962356, lng: 11.3519683},
        "name": "Dr paolo garagnani",
        "phone": "+390512094776",
        "yearOfBirth": "1973",
        "yearsSincePHD": "8"
    },
    {
        "affiliationCategory": "COST International Partners",
        "country": "Japan",
        "email": "ashir@ait.kyushu",
        "expertise": "Computer and Information Sciences (Artificial intelligence, intelligent systems, multi agent systems)",
        "gender": "Male",
        "institution": "Kyushu University",
        "location": {lat: 33.6266628, lng: 130.4228558},
        "name": "Dr Ashir Ahmed",
        "phone": "+81928023632",
        "yearOfBirth": "1970",
        "yearsSincePHD": "17"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Netherlands",
        "email": "j.hoeijmakers@erasmusmc.nl",
        "expertise": "Biological sciences (Molecular genetics, reverse genetics and RNAi)",
        "gender": "Male",
        "institution": "Erasmus University Medical Center Rotterdam",
        "location": {lat: 51.9100414, lng: 4.4636287},
        "name": "Prof Jan Hoeijmakers",
        "phone": "+31107043199",
        "yearOfBirth": "1951",
        "yearsSincePHD": "35"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Norway",
        "email": "av@digitalbiopharm.com",
        "expertise": "Chemical sciences (Theoretical and computational chemistry)",
        "gender": "Male",
        "institution": "Digital BioPharm AS",
        "location": {lat: 59.8939529, lng: 10.645035},
        "name": "Dr Andrey Voronkov",
        "phone": "+4746227796",
        "yearOfBirth": "1982",
        "yearsSincePHD": "7"
    },
    {
        "affiliationCategory": "COST International Partners",
        "country": "Pakistan",
        "email": "aftab.nays@gmail.com",
        "expertise": "Biological sciences (Stem cell biology)",
        "gender": "Male",
        "institution": "National Academy of Young Scientists",
        "location": {lat: 33.6693413, lng: 72.8448924},
        "name": "Dr Aftab Ahmad Chattha",
        "phone": "+923007402202",
        "yearOfBirth": "1982",
        "yearsSincePHD": "1"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Poland",
        "email": "e.sikora@nencki.gov.pl",
        "expertise": "Health Sciences (biogerontology)",
        "gender": "Female",
        "institution": "Nencki Institute of Experimental Bioloy",
        "location": {lat: 52.2134164, lng: 20.981191},
        "name": "Prof Ewa Sikora",
        "phone": "+48225298251",
        "yearOfBirth": "1953",
        "yearsSincePHD": "33"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Portugal",
        "email": "ccavadas@uc.pt",
        "expertise": "Basic medicine (Neurochemistry and neuropharmacology)",
        "gender": "Female",
        "institution": "CNC - Center of Neuroscience and Cell Biology",
        "location": {lat: 40.2086884, lng: -8.4263865},
        "name": "Prof Claudia Cavadas",
        "phone": "+351963928766",
        "yearOfBirth": "1967",
        "yearsSincePHD": "14"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Portugal",
        "email": "nkazachkova@yahoo.com",
        "expertise": "Biological sciences (Molecular genetics, reverse genetics and RNAi)",
        "gender": "Female",
        "institution": "Scientific Innovations Azores",
        "location": {lat: 38.7437396, lng: -9.2302438},
        "name": "Dr Nadiya Kazachkova",
        "phone": "+968022532",
        "yearOfBirth": "1976",
        "yearsSincePHD": "9"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Romania",
        "email": "robi.tacutu@gmail.com",
        "expertise": "Biological sciences (Biogerontology)",
        "gender": "Male",
        "institution": "Institute of Biochemistry Bucharest",
        "location": {lat: 44.4470396, lng: 26.0436353},
        "name": "Dr Robi Tacutu",
        "phone": "+40722311751",
        "yearOfBirth": "1981",
        "yearsSincePHD": "3"
    },
    {
        "affiliationCategory": "Near-Neighbour Country Institutions",
        "country": "Russian Federation",
        "email": "khaltourina@yahoo.com",
        "expertise": "Other medical sciences (Databases, data mining, data curation, computational modelling for other medical sciences)",
        "gender": "Female",
        "institution": "Federal State Institution 'National Research Center for Preventive Medicine' of the Ministry of Healthcare of the Russian Federation [Department of the Integrated Prevention Programs]",
        "location": {lat: 55.7498598, lng: 37.3523184},
        "name": "Dr Daria Khaltourina",
        "phone": "+79262213024",
        "yearOfBirth": "1979",
        "yearsSincePHD": "13"
    },
    {
        "affiliationCategory": "Near-Neighbour Country Institutions",
        "country": "Russian Federation",
        "email": "amoskalev@list.ru",
        "expertise": "Biological sciences (Genomics, comparative genomics, functional genomics)",
        "gender": "Male",
        "institution": "Moscow Institute of Physics and Technology",
        "location": {lat: 55.930218, lng: 37.5160213},
        "name": "Prof Alexey Moskalev",
        "phone": "+79121498300",
        "yearOfBirth": "1976",
        "yearsSincePHD": "12"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Serbia",
        "email": "anamikos@ibiss.bg.ac.rs",
        "expertise": "Biological sciences (Molecular biology and interactions)",
        "gender": "Female",
        "institution": "Institute for Biological Research - Institute for Biological Research 'Sinisa Stankovic'",
        "location": {lat: 44.8173604, lng: 18.2460225},
        "name": "Dr Aleksandra Mladenovic Djordjevic",
        "phone": "+381112078337",
        "yearOfBirth": "1973",
        "yearsSincePHD": "8"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Serbia",
        "email": "gerijatar@gmail.com",
        "expertise": "Clinical medicine (Geriatrics and gerontology)",
        "gender": "Male",
        "institution": "Serbian Association of geriatricians and gerontologist",
        "location": {lat: 44.8154033, lng: 20.2825133},
        "name": "Prof Mladen Davidovic",
        "phone": "+38163288727",
        "yearOfBirth": "1946",
        "yearsSincePHD": "26"
    },
    {
        "affiliationCategory": "COST International Partners",
        "country": "Singapore",
        "email": "anis_larbi@immunol.a",
        "expertise": "Biological sciences (Biological basis of immunity related disorders)",
        "gender": "Male",
        "institution": "Agency for Science Technology and Research",
        "location": {lat: 1.3150701, lng: 103.7069328},
        "name": "Dr Anis Larbi",
        "phone": "+6586464748",
        "yearOfBirth": "1979",
        "yearsSincePHD": "11"
    },
    {
        "affiliationCategory": "COST International Partners",
        "country": "South Korea",
        "email": "minkj@inha.ac.kr",
        "expertise": "Biological sciences (Zoology, including animal behaviour)",
        "gender": "Male",
        "institution": "Inha University - inha univ",
        "location": {lat: 37.4496312, lng: 126.6509273},
        "name": "Prof Kyung-Jin Min",
        "phone": "+82328608193",
        "yearOfBirth": "1970",
        "yearsSincePHD": "13"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Spain",
        "email": "salvador.ventura@uab.es",
        "expertise": "Biological sciences (Biophysics)",
        "gender": "Male",
        "institution": "Universitat Autònoma de Barcelona",
        "location": {lat: 41.5026859, lng: 2.1021331},
        "name": "Prof Salvador Ventura",
        "phone": "+34935868956",
        "yearOfBirth": "1967",
        "yearsSincePHD": "18"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Spain",
        "email": "rperona@iib.uam.es",
        "expertise": "Basic medicine (Cell signalling and cellular interactions)",
        "gender": "Female",
        "institution": "Consejo Superior de Investigaciones Cientificas",
        "location": {lat: 40.9616386, lng: -2.9882774},
        "name": "Prof Rosario Perona",
        "phone": "+34915854463",
        "yearOfBirth": "1956",
        "yearsSincePHD": "31"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Spain",
        "email": "inma.ibanezca@salud.madrid.org",
        "expertise": "Medical biotechnology (Epigenetics and gene regulation for medical biotechnology)",
        "gender": "Female",
        "institution": "Hospital La Paz Institute for Health Research",
        "location": {lat: 40.4811674, lng: -3.689587},
        "name": "Dr Inmaculada Ibanez de Caceres",
        "phone": "+34912071010",
        "yearOfBirth": "1974",
        "yearsSincePHD": "14"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Spain",
        "email": "antonio.cano@uv.es",
        "expertise": "Clinical medicine (Obstetrics and gynaecology)",
        "gender": "Male",
        "institution": "University of Valencia",
        "location": {lat: 39.4793295, lng: -0.361575},
        "name": "Prof Antonio Cano",
        "phone": "+963864170",
        "yearOfBirth": "1954",
        "yearsSincePHD": "37"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Sweden",
        "email": "huixin.wang@su.se",
        "expertise": "Health Sciences (Epidemiology)",
        "gender": "Female",
        "institution": "Stockholm University",
        "location": {lat: 59.3627674, lng: 18.057079},
        "name": "Prof Hui-Xin Wang",
        "phone": "+46855378918",
        "yearOfBirth": "1964",
        "yearsSincePHD": "15"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Sweden",
        "email": "",
        "expertise": "Health Sciences (Epidemiology)",
        "gender": "Female",
        "institution": "Karolinska Institutet - Department of Neurobiology",
        "location": {lat: 59.3476756, lng: 18.0249777},
        "name": "Dr Anna-Karin Welmer",
        "phone": "+4686906866",
        "yearOfBirth": "1976",
        "yearsSincePHD": "9"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Switzerland",
        "email": "admin.auwerx@epfl.ch",
        "expertise": "Health Sciences (Nutrition and dietetics)",
        "gender": "Male",
        "institution": "Ecole Polytechnique Federale de Lausanne",
        "location": {lat: 46.5190594, lng: 6.5645689},
        "name": "Prof Johan Auwerx",
        "phone": "+41 21 693 95 22",
        "yearOfBirth": "1958",
        "yearsSincePHD": "26"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "Turkey",
        "email": "michelle@bilkent.edu.tr",
        "expertise": "Biological sciences (Neuroscience Cellular Molecular Developmental)",
        "gender": "Female",
        "institution": "Bilkent University",
        "location": {lat: 39.8746188, lng: 32.7454075},
        "name": "Dr Michelle Adams",
        "phone": "+903122903415",
        "yearOfBirth": "1968",
        "yearsSincePHD": "15"
    },
    {
        "affiliationCategory": "Near-Neighbour Country Institutions",
        "country": "Ukraine",
        "email": "sensus.sextus@gmail.com",
        "expertise": "Computer and Information Sciences (Artificial intelligence, intelligent systems, multi agent systems)",
        "gender": "Male",
        "institution": "Institute of Cybernetics of NASU [Dept of Neural Technologies]",
        "location": {lat: 50.4021368, lng: 30.2525107},
        "name": "Dr Dimitri Nowicki",
        "phone": "+48123613390",
        "yearOfBirth": "1976",
        "yearsSincePHD": "9"
    },
    {
        "affiliationCategory": "Near-Neighbour Country Institutions",
        "country": "Ukraine",
        "email": "vaiserman23@gmail.com",
        "expertise": "Biological sciences (Epigenetics and gene regulation)",
        "gender": "Male",
        "institution": "Instiute of Gerontology",
        "location": {lat: 50.5191127, lng: 30.4466772},
        "name": "Prof Alexander Vaiserman",
        "phone": "+380444310558",
        "yearOfBirth": "1957",
        "yearsSincePHD": "25"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "United Kingdom",
        "email": "aging@liv.ac.uk",
        "expertise": "Biological sciences (Genomics, comparative genomics, functional genomics)",
        "gender": "Male",
        "institution": "University of Liverpool",
        "location": {lat: 53.4059392, lng: -2.9677609},
        "name": "Dr Joao Pedro Magalhaes",
        "phone": "+441517954517",
        "yearOfBirth": "1977",
        "yearsSincePHD": "12"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "United Kingdom",
        "email": "Stolzing@gmail.com",
        "expertise": "Medical biotechnology (Gene therapy, stem cell therapy, regenerative medicine for medical biotechnology)",
        "gender": "Female",
        "institution": "Loughborough University [Wolfson School of Mechanical Engineering]",
        "location": {lat: 52.7692302, lng: -1.2268207},
        "name": "Dr Alexandra Stolzing",
        "phone": "+49341355363405",
        "yearOfBirth": "1973",
        "yearsSincePHD": "12"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "United Kingdom",
        "email": "hevok@denigma.de",
        "expertise": "Biological sciences (Computational biology)",
        "gender": "Male",
        "institution": "Integrative Genomics of Aging Research Group - University of Liverpool [Department of Functional and Comparative Genomics / Integrative Genomics of Ageing Group]",
        "location": {lat: 52.7692300, lng: -1.2268200},
        "name": "Mr Daniel Wuttke",
        "phone": "+4915782321960",
        "yearOfBirth": "1985",
        "yearsSincePHD": "0"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "United Kingdom",
        "email": "info@deepknowledge.life",
        "expertise": "Health Sciences (Health services, health care research)",
        "gender": "Male",
        "institution": "Deep Knowledge Life Science",
        "location": {lat: 51.5287718, lng: -0.2416814},
        "name": "Mr Aleksei Petikov",
        "phone": "+9028022146",
        "yearOfBirth": "1983",
        "yearsSincePHD": "2"
    },
    {
        "affiliationCategory": "COST Country Institutions",
        "country": "United Kingdom",
        "email": "davidw@deltawisdom.com",
        "expertise": "Media and communications (Media and communications, social aspects of information science and surveillance, socio-cultural communication)",
        "gender": "Male",
        "institution": "Delta Wisdom",
        "location": {lat: 51.5287720, lng: -0.2416820},
        "name": "Dr David Wood",
        "phone": "+447899803858",
        "yearOfBirth": "1959",
        "yearsSincePHD": "11"
    },
    {
        "affiliationCategory": "COST International Partners",
        "country": "United States",
        "email": "kunlin.jin@unthsc.edu",
        "expertise": "Biological sciences (Stem cell biology)",
        "gender": "Male",
        "institution": "International society on Aging and Disease",
        "location": {lat: 47.257373, lng: -123.0936473},
        "name": "Prof Kunlin Jin",
        "phone": "+8177352579",
        "yearOfBirth": "1960",
        "yearsSincePHD": "25"
    },
    {
        "affiliationCategory": "COST International Partners",
        "country": "United States",
        "email": "vera.gorbunova@rochester.edu",
        "expertise": "Biological sciences (Cell genetics)",
        "gender": "Female",
        "institution": "University of Rochester",
        "location": {lat: 43.130557, lng: -77.628192},
        "name": "Prof Vera Gorbunova",
        "phone": "+15852757740",
        "yearOfBirth": "1971",
        "yearsSincePHD": "16"
    }
];

export {gerontologists};