const gerontologists = [
    {
        name: "Ms Alyse Sue",
        gender: "female",
        country: "Australia",
        yearOfBirth: 1988,
        yearsSincePHD: 0,
        institution: "Genomix",
        email: "alyse.sue@genomix.co",
        phone: "+61405838333",
        affiliationCategory: "COST International Partners",
        expertise: "Computer and Information Sciences (Regenerative medicine for life and health extension)",
        location: {lat: -35.3136188, lng: 148.9896987}
    },
    {
        name: "Prof Barbara Strasser",
        gender: "female",
        country: "Austria",
        yearOfBirth: 1972,
        yearsSincePHD: 8,
        institution: "Medical University Innsbruck",
        email: "Barbara.Strasser@i-med.ac.at",
        phone: "+436642083316",
        affiliationCategory: "COST Country Institutions",
        expertise: "Health Sciences (Sport and fitness sciences)",
        location: {lat: 47.262698, lng: 11.3827692}
    },
    {
        name: "Dr Rafiqul Islam",
        gender: "male",
        country: "Bangladesh",
        yearOfBirth: 1967,
        yearsSincePHD: 19,
        institution: "Grameen Communications",
        email: "rimaruf@grameen.com",
        phone: "+88029016391",
        affiliationCategory: "COST International Partners",
        expertise: "Electrical engineering, electronic engineering, Information engineering (Communications engineering and systems)",
        location: {lat: 23.1943498, lng: 87.7778257}
    },
    {
        name: "Mr Didier Coeurnelle",
        gender: "male",
        country: "Belgium",
        yearOfBirth: 1962,
        yearsSincePHD: 0,
        email: "didier.coeurnelle@gmail.com",
        phone: "+3224105956",
        institution: "Heales",
        affiliationCategory: "COST Country Institutions",
        expertise: "Health Sciences (Health services, health care research)",
        location: {lat: 51.2605163, lng: 4.2304522}
    },
    {
        name: "Prof Liesbet Temmerman",
        gender: "female",
        country: "Belgium",
        yearOfBirth: 1985,
        yearsSincePHD: 5,
        institution: "University of Leuven (KU Leuven)",
        email: "Liesbet.Temmerman@bio.kuleuven.be",
        phone: "+3216324260",
        affiliationCategory: "COST Country Institutions",
        expertise: "Biological sciences (Molecular biology and interactions)",
        location: {lat: 50.8779579, lng: 4.6981066}
    },
    {
        name: "Mr Arne Smolders",
        gender: "male",
        country: "Belgium",
        yearOfBirth: 1988,
        yearsSincePHD: 0,
        institution: "AcademicLabs",
        email: "arne@academiclabs.co",
        phone: "+32479509327",
        affiliationCategory: "COST Country Institutions",
        expertise: "Biological sciences (Zoology, including animal behaviour)",
        location: {lat: 51.2605160, lng: 4.2304500}
    },
    {
        name: "Prof Angel Marchev",
        gender: "male",
        country: "Bulgaria",
        yearOfBirth: 1946,
        yearsSincePHD: 35,
        institution: "University of National and World Economy",
        email: "angel_marchev@yahoo.co.uk",
        phone: "+35929833991",
        affiliationCategory: "COST Country Institutions",
        expertise: "Economics and business (Databases, data mining, data curation, computational modelling)",
        location: {lat: 42.6512699, lng: 23.3466593}
    },
    {
        name: "Dr Arnold Mitnitski",
        gender: "male",
        country: "Canada",
        yearOfBirth: 1944,
        yearsSincePHD: 42,
        email: "arnold.mitnitski@dal.ca",
        phone: "+9024460460",
        institution: "Dalhousie University",
        affiliationCategory: "COST International Partners",
        expertise: "Health Sciences (Applied mathematics, statistics, non-computational modeling for health sciences)",
        location: {lat: 44.636585, lng: -63.5938442}
    },
    {
        name: "Prof Tamas Fulop",
        gender: "male",
        country: "Canada",
        yearOfBirth: 1953,
        yearsSincePHD: 31,
        email: "tamas.fulop@usherbrooke.ca",
        phone: "+18197802220",
        institution: "Université de Sherbrooke - Faculté de médecine et des Sciences de la santé",
        affiliationCategory: "COST International Partners",
        expertise: "Basic medicine (Cell signalling and cellular interactions)",
        location: {lat: 45.3768923, lng: -71.9277091}
    },
    {
        name: "Dr Marios Kyriazis",
        gender: "male",
        country: "Cyprus",
        yearOfBirth: 1956,
        yearsSincePHD: 32,
        email: "drmarios@live.it",
        phone: "+447850221796",
        institution: "Cyprus Neuroscienec and Technology Institute - CNTI",
        affiliationCategory: "COST Country Institutions",
        expertise: "Biological sciences (Biology of Ageing)",
        location: {lat: 35.165786, lng: 33.3569552}
    },
    {
        name: "Prof Fofi Constantinidou",
        gender: "female",
        country: "Cyprus",
        yearOfBirth: 1966,
        yearsSincePHD: 21,
        email: "fofic@ucy.ac.cy",
        phone: "+35722892078",
        institution: "University of Cyprus [Center for Applied Neuroscience]",
        affiliationCategory: "COST Country Institutions",
        expertise: "-",
        location: {lat: 35.1600058, lng: 33.3748288}
    }
];

export {gerontologists};